![This is an image](Quant-Trading.jpg)

<font size="3">
Please visit our website <a href="https://www.quant-trading.co" target="_blank">quant-trading.co</a> for more tools on quantitative finance and data science.
</font>

In [1]:
# !pip install pandas-datareader

# **WORLDBANK API**

## **¿What can you download using this API?**

<font size="3"> The World Bank Indicators API provides access to nearly 16,000 time series indicators. Most of these indicators are available online through tools such as Databank and the Open Data website. The API provides programmatic access to this same data. Many data series date back over 50 years, and can be used to create interesting applications.<br><br>

<font size="3"> The Indicators API provides access to over 45 databases, including:<br><br>

World Development Indicators<br><br>
International Debt Statistcs<br><br>
Doing Business<br><br>
Human Capital Index<br><br>
Subnational Poverty<br><br>

<font size="3">
The pandas_datareader library allows you to fetch data from different sources, including Yahoo Finance for financial market data, World Bank for global development data, and St. Louis Fed for economic data. In this notebook, we’ll show how you can load data from WORLDBANK. Behind the scene, pandas_datareader pulls the data you want from the web in real time and assembles it into a pandas DataFrame. Because of the vastly different structure of web pages, each data source needs a different reader. Hence, pandas_datareader only supports reading from a limited number of sources, mostly related to financial and economic time series. Below you can find an example on how this works.

In [2]:
import warnings
warnings.filterwarnings('ignore')

from pandas_datareader import wb  #Pandas Datareader
import datetime

## **Inspect all the countries available in the database**

<font size="3"> One of the important features of the WorldBank database is that it contains a lot of indicators for different countries. You can download a DataFrame that contains most of the countries in the world with some classifications such as Income Level or Region. You can also get the iso code which is a identifier you can use to combine with other databases.
<br><br>

In [3]:
countries = wb.get_countries()
countries

,iso3c,iso2c,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,,Aggregates,Aggregates,,NaN,NaN
2,AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,NaN,NaN
4,AFW,ZI,Africa Western and Central,Aggregates,,Aggregates,Aggregates,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,,Aggregates,Aggregates,,NaN,NaN
292,YEM,YE,"Yemen, Rep.",Middle East & North Africa,Middle East & North Africa (excluding high inc...,Low income,IDA,Sana'a,44.2075,15.3520
293,ZAF,ZA,South Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD,Pretoria,28.1871,-25.7460
294,ZMB,ZM,Zambia,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IDA,Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,Harare,31.0672,-17.8312

## **Select particular countries**

<font size="3"> You can select particular rows in a DataFrame using the loc function. Below you can see an example where we select de countries DataFrame in the field region, and select the rows that are equal to 'Europe & Central Asia'. That script will select all the countries that belong to this region. 
<br><br>

In [4]:
europe_countries = countries.loc[countries['region']=='Europe & Central Asia']
europe_countries.head(10)

,iso3c,iso2c,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
6,ALB,AL,Albania,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Tirane,19.81720,41.3317
7,AND,AD,Andorra,Europe & Central Asia,,High income,Not classified,Andorra la Vella,1.52180,42.5075
11,ARM,AM,Armenia,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Yerevan,44.50900,40.1596
15,AUT,AT,Austria,Europe & Central Asia,,High income,Not classified,Vienna,16.37980,48.2201
16,AZE,AZ,Azerbaijan,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Baku,49.89320,40.3834
20,BEL,BE,Belgium,Europe & Central Asia,,High income,Not classified,Brussels,4.36761,50.8371
24,BGR,BG,Bulgaria,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Sofia,23.32380,42.7105
28,BIH,BA,Bosnia and Herzegovina,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Sarajevo,18.42140,43.8607
30,BLR,BY,Belarus,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Minsk,27.57660,53.9678
47,CHE,CH,Switzerland,Europe & Central Asia,,High income,Not classified,Bern,7.44821,46.9480

## **Inspect all the indicators available in the database**

<font size="3"> You can get all the indicators using the function get_indicators(). As you can see below, the list contains 24.114 different indicators.
<br><br>

In [5]:
#Download information about all World Bank data series
indicators = wb.get_indicators()
indicators

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of data from Nati...,Poverty
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
...,...,...,...,...,...,...,...
24408,w_F_skl,Annual wage for skilled female workers in US$,,Gender Disaggregated Labor Database (GDLD),,b'',
24409,w_M_nsk,Annual wage for unskilled male workers in US$,,Gender Disaggregated Labor Database (GDLD),,b'',
24410,w_M_skl,Annual wage for skilled male workers in US$,,Gender Disaggregated Labor Database (GDLD),,b'',
24411,wpremia_F,Wage Premia for Females (the ratio of skilled ...,,Gender Disaggregated Labor Database (GDLD),,b'',
24412,wpremia_M,Wage Premia for Males (the ratio of skilled m...,,Gender Disaggregated Labor Database (GDLD),,b'',

## **Select specific indicators**

<font size="3"> As we showed before, you can select particular rows in a DataFrame using the loc function. Instead of using the operator equal to, we will use the function str.contains . That functions allows us to look for a particular text and select all the rows that contain that text. In this case we are looking for all rows that contain the word 'Poverty" in the field name as shown below.
<br><br>

In [6]:
poverty_indicators = indicators.loc[indicators['name'].str.contains('Poverty')]
poverty_indicators

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of data from Nati...,Poverty
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
6,1.0.PGap.1.90usd,Poverty Gap ($1.90 a day),,LAC Equity Lab,The poverty gap captures the mean aggregate in...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
...,...,...,...,...,...,...,...
24364,per_si_ss_p0_urb,Poverty Headcount reduction (%) - Other Socia...,,The Atlas of Social Protection: Indicators of ...,Poverty headcount reduction due to Other Socia...,b'ASPIRE',Social Protection & Labor
24365,per_si_ss_p1_ep_tot,Poverty Gap reduction (%) - Other Social Insu...,,The Atlas of Social Protection: Indicators of ...,Poverty gap reduction due to Other Social Insu...,b'ASPIRE',Social Protection & Labor
24366,per_si_ss_p1_rur,Poverty Gap reduction (%) - Other Social Insu...,,The Atlas of Social Protection: Indicators of ...,Poverty gap reduction due to Other Social Insu...,b'ASPIRE',Social Protection & Labor
24367,per_si_ss_p1_tot,Poverty Gap reduction (%) - Other Social Insu...,,The Atlas of Social Protection: Indicators of ...,Poverty gap reduction due to Other Social Insu...,b'ASPIRE',Social Protection & Labor
24368,per_si_ss_p1_urb,Poverty Gap reduction (%) - Other Social Insu...,,The Atlas of Social Protection: Indicators of ...,Poverty gap reduction due to Other Social Insu...,b'ASPIRE',Social Protection & Labor

## **Search function**

<font size="3"> You can use the function search to look for particular information on the database. You just need to write the words you are looking for, and the function will return all the rows that contain that information. In the example below you can see what we get when we write "GDP per capita". 
<br><br>

In [7]:
#Search available data series from the world bank
gdp_per_capita_data = wb.search("GDP per capita")
gdp_per_capita_data

,id,name,unit,source,sourceNote,sourceOrganization,topics
691,6.0.GDPpc_constant,"GDP per capita, PPP (constant 2011 internation...",,LAC Equity Lab,GDP per capita based on purchasing power parit...,b'World Development Indicators (World Bank)',Economy & Growth
2410,CC.GHG.MEMG.GC,Macro drivers of GHG emissions growth in the p...,,Country Climate and Development Report (CCDR),Data reflects the impact of GDP-per capita (as...,"b'Climate Watch. 2020. Washington, DC: World R...",
6388,FB.DPT.INSU.PC.ZS,Deposit insurance coverage (% of GDP per capita),,WDI Database Archives,,b'',
10758,NV.AGR.PCAP.KD.ZG,Real agricultural GDP per capita growth rate (%),,Africa Development Indicators,The growth rate of real per capita GDP in agri...,b'World Bank country economists.',
10978,NY.GDP.PCAP.CD,GDP per capita (current US$),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10979,NY.GDP.PCAP.CN,GDP per capita (current LCU),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10980,NY.GDP.PCAP.KD,GDP per capita (constant 2015 US$),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10981,NY.GDP.PCAP.KD.ZG,GDP per capita growth (annual %),,World Development Indicators,Annual percentage growth rate of GDP per capit...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10982,NY.GDP.PCAP.KN,GDP per capita (constant LCU),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10983,NY.GDP.PCAP.PP.CD,"GDP per capita, PPP (current international $)",,World Development Indicators,This indicator provides per capita values for ...,"b'International Comparison Program, World Bank...",Economy & Growth
10984,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2017 internation...",,World Development Indicators,GDP per capita based on purchasing power parit...,"b'International Comparison Program, World Bank...",Economy & Growth
10985,NY.GDP.PCAP.PP.KD.87,"GDP per capita, PPP (constant 1987 internation...",,WDI Database Archives,,b'',
10986,NY.GDP.PCAP.PP.KD.ZG,"GDP per capita, PPP annual growth (%)",,Africa Development Indicators,Annual percentage growth rate of GDP per capit...,"b'""World Bank, International Comparison Progra...",
11205,PER.ALL.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11282,PER.BAS.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11349,PER.JR.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11492,PER.PP.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11559,PER.PRM.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11653,PER.SEC.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11888,PER.SR.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11945,PER.TER.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
11992,PER.TT.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
12012,PER.VOC.PS.GDP,World Bank: Public education expenditure per s...,,Education Statistics,,b'',
15668,SE.PRM.SATT.2,(De Facto) Average principal salary as percent...,,Education Statistics,,"b'World Bank, Global Education Policy Dashboard'",
15732,SE.PRM.TATT.1,(De Jure) Average starting public-school teach...,,Education Statistics,,"b'World Bank, Global Education Policy Dashboard'",
15965,SE.XPD.PRIM.PC.ZS,"Government expenditure per student, primary (%...",,World Development Indicators,Government expenditure per student is the aver...,b'UNESCO Institute for Statistics (http://uis....,Education
15969,SE.XPD.SECO.PC.ZS,"Government expenditure per student, secondary ...",,World Development Indicators,Government expenditure per student is the aver...,b'UNESCO Institute for Statistics (http://uis....,Education
15974,SE.XPD.TERT.PC.ZS,"Government expenditure per student, tertiary (...",,World Development Indicators,Government expenditure per student is the aver...,b'UNESCO Institute for Statistics (http://uis....,Education
20239,UIS.XUNIT.GDPCAP.02.FSGOV,Initial government funding per pre-primary stu...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20240,UIS.XUNIT.GDPCAP.1.FSGOV,Initial government funding per primary student...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20241,UIS.XUNIT.GDPCAP.1.FSHH,Initial household funding per primary student ...,,Education Statistics,"Total payments of households (pupils, students...",b'UNESCO Institute for Statistics',
20242,UIS.XUNIT.GDPCAP.2.FSGOV,Initial government funding per lower secondary...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20243,UIS.XUNIT.GDPCAP.23.FSGOV,Initial government funding per secondary stude...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20244,UIS.XUNIT.GDPCAP.23.FSHH,Initial household funding per secondary studen...,,Education Statistics,"Total payments of households (pupils, students...",b'UNESCO Institute for Statistics',
20245,UIS.XUNIT.GDPCAP.3.FSGOV,Initial government funding per upper secondary...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20246,UIS.XUNIT.GDPCAP.5T8.FSGOV,Initial government funding per tertiary studen...,,Education Statistics,"Total general (local, regional and central, cu...",b'UNESCO Institute for Statistics',
20247,UIS.XUNIT.GDPCAP.5T8.FSHH,Initial household funding per tertiary student...,,Education Statistics,"Total payments of households (pupils, students...",b'UNESCO Institute for Statistics',

## **Download history for an specific indicator**

<font size="3"> As you can see in the table above, there are a lot of different indicators related with GDP per Capita. We can choose the one that reads "GDP per capita (current US$)", which is measured in actual dollar terms. If you look in the column id, you will find that the indicator is "NY.GDP.PCAP.CD". Let's use that id to get a time series of this information. 
<br><br>

In [8]:
my_indicator = 'NY.GDP.PCAP.CD'
my_indicator_history1 = wb.download(indicator = my_indicator)
my_indicator_history1

                    NY.GDP.PCAP.CD
country       year
Canada        2005    36382.507916
              2004    32143.681408
              2003    28300.463096
Mexico        2005     8702.114481
              2004     7883.523191
              2003     7473.932375
United States 2005    44123.407068
              2004    41724.631629
              2003    39490.274956

## **Download history for an specific indicator for a time period**

<font size="3"> You can specify which time period you would like to download as it is shown below. 
<br><br>

In [9]:
#DATES
start_date = datetime.datetime(2013, 12, 31)
end_date = datetime.datetime(2023, 12, 31)

my_indicator_history2 = wb.download(indicator = my_indicator, start=start_date,end=end_date)
my_indicator_history2

                    NY.GDP.PCAP.CD
country       year
Canada        2022    54917.662523
              2021    52358.621641
              2020    43349.677856
              2019    46374.152752
              2018    46548.638411
              2017    45129.429298
              2016    42315.603706
              2015    43596.135537
              2014    50955.998323
              2013    52635.174958
Mexico        2022    11496.522872
              2021    10359.149863
              2020     8894.890650
              2019    10434.578365
              2018    10130.320698
              2017     9693.330091
              2016     9152.737223
              2015    10098.173181
              2014    11490.021690
              2013    11317.491061
United States 2022    76329.582265
              2021    70219.472454
              2020    63528.634303
              2019    65120.394663
              2018    62823.309438
              2017    59907.754261
              2016    57866.744934
              2015    56762.729452
              2014    55123.849787
              2013    53291.127689

## **Download history for an specific indicator and specific country for a time period**

<font size="3"> You can also specify a particular country using the following script. 
<br><br>

In [10]:
my_indicator_history3 = wb.download(indicator = my_indicator, start=start_date,end=end_date, country = 'BR')
my_indicator_history3

              NY.GDP.PCAP.CD
country year
Brazil  2022     8917.674911
        2021     7696.784830
        2020     6923.699912
        2019     8845.324149
        2018     9121.020995
        2017     9896.718895
        2016     8680.736469
        2015     8783.215424
        2014    12071.404464
        2013    12258.565709

## **Download history for an specific indicator and specific countries for a time period**

<font size="3"> You can even do that for multiple countries as shown below. 
<br><br>

In [11]:
my_indicator_history4 = wb.download(indicator = my_indicator, start=start_date,end=end_date, country = ['BR','MX','CL'])
my_indicator_history4

              NY.GDP.PCAP.CD
country year
Brazil  2022     8917.674911
        2021     7696.784830
        2020     6923.699912
        2019     8845.324149
        2018     9121.020995
        2017     9896.718895
        2016     8680.736469
        2015     8783.215424
        2014    12071.404464
        2013    12258.565709
Chile   2022    15355.479740
        2021    16240.607776
        2020    13173.784794
        2019    14632.690308
        2018    15820.033357
        2017    15034.058425
        2016    13788.240016
        2015    13567.357217
        2014    14675.150873
        2013    15842.159157
Mexico  2022    11496.522872
        2021    10359.149863
        2020     8894.890650
        2019    10434.578365
        2018    10130.320698
        2017     9693.330091
        2016     9152.737223
        2015    10098.173181
        2014    11490.021690
        2013    11317.491061

If this content is helpful and you want to make a donation please click on the button

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=29CVY97MEQ9BY)